// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: moon-phase-round

#ifndef _MOON_PHASE_ROUND_UI_H
#define _MOON_PHASE_ROUND_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * moon_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_bg_png);    // assets/bg.png
LV_IMG_DECLARE(ui_img_earth_png);    // assets/earth.png
LV_IMG_DECLARE(ui_img_moon_moon_1_png);    // assets/Moon/Moon_1.png
LV_IMG_DECLARE(ui_img_moon_moon_10_png);    // assets/Moon/Moon_10.png
LV_IMG_DECLARE(ui_img_moon_moon_11_png);    // assets/Moon/Moon_11.png
LV_IMG_DECLARE(ui_img_moon_moon_12_png);    // assets/Moon/Moon_12.png
LV_IMG_DECLARE(ui_img_moon_moon_13_png);    // assets/Moon/Moon_13.png
LV_IMG_DECLARE(ui_img_moon_moon_14_png);    // assets/Moon/Moon_14.png
LV_IMG_DECLARE(ui_img_moon_moon_15_png);    // assets/Moon/Moon_15.png
LV_IMG_DECLARE(ui_img_moon_moon_16_png);    // assets/Moon/Moon_16.png
LV_IMG_DECLARE(ui_img_moon_moon_17_png);    // assets/Moon/Moon_17.png
LV_IMG_DECLARE(ui_img_moon_moon_18_png);    // assets/Moon/Moon_18.png
LV_IMG_DECLARE(ui_img_moon_moon_19_png);    // assets/Moon/Moon_19.png
LV_IMG_DECLARE(ui_img_moon_moon_2_png);    // assets/Moon/Moon_2.png
LV_IMG_DECLARE(ui_img_moon_moon_20_png);    // assets/Moon/Moon_20.png
LV_IMG_DECLARE(ui_img_moon_moon_21_png);    // assets/Moon/Moon_21.png
LV_IMG_DECLARE(ui_img_moon_moon_22_png);    // assets/Moon/Moon_22.png
LV_IMG_DECLARE(ui_img_moon_moon_23_png);    // assets/Moon/Moon_23.png
LV_IMG_DECLARE(ui_img_moon_moon_24_png);    // assets/Moon/Moon_24.png
LV_IMG_DECLARE(ui_img_moon_moon_25_png);    // assets/Moon/Moon_25.png
LV_IMG_DECLARE(ui_img_moon_moon_26_png);    // assets/Moon/Moon_26.png
LV_IMG_DECLARE(ui_img_moon_moon_27_png);    // assets/Moon/Moon_27.png
LV_IMG_DECLARE(ui_img_moon_moon_28_png);    // assets/Moon/Moon_28.png
LV_IMG_DECLARE(ui_img_moon_moon_29_png);    // assets/Moon/Moon_29.png
LV_IMG_DECLARE(ui_img_moon_moon_3_png);    // assets/Moon/Moon_3.png
LV_IMG_DECLARE(ui_img_moon_moon_30_png);    // assets/Moon/Moon_30.png
LV_IMG_DECLARE(ui_img_moon_moon_4_png);    // assets/Moon/Moon_4.png
LV_IMG_DECLARE(ui_img_moon_moon_5_png);    // assets/Moon/Moon_5.png
LV_IMG_DECLARE(ui_img_moon_moon_6_png);    // assets/Moon/Moon_6.png
LV_IMG_DECLARE(ui_img_moon_moon_7_png);    // assets/Moon/Moon_7.png
LV_IMG_DECLARE(ui_img_moon_moon_8_png);    // assets/Moon/Moon_8.png
LV_IMG_DECLARE(ui_img_moon_moon_9_png);    // assets/Moon/Moon_9.png

// FONTS
LV_FONT_DECLARE(ui_font_datefont);
LV_FONT_DECLARE(ui_font_timefont);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
