// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.1
// LVGL version: 8.3.11
// Project name: moon-phase-round

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_starsbg = NULL;
lv_obj_t * ui_img_earth = NULL;
lv_obj_t * ui_img_moon = NULL;
lv_obj_t * ui_phase = NULL;
lv_obj_t * ui_time = NULL;
lv_obj_t * ui_date = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_starsbg = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_starsbg, &ui_img_bg_png);
    lv_obj_set_width(ui_starsbg, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_starsbg, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_x(ui_starsbg, 0);
    lv_obj_set_y(ui_starsbg, -19);
    lv_obj_set_align(ui_starsbg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_starsbg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_starsbg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_earth = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_img_earth, &ui_img_earth_png);
    lv_obj_set_width(ui_img_earth, LV_SIZE_CONTENT);   /// 240
    lv_obj_set_height(ui_img_earth, LV_SIZE_CONTENT);    /// 78
    lv_obj_set_x(ui_img_earth, -8);
    lv_obj_set_y(ui_img_earth, 82);
    lv_obj_set_align(ui_img_earth, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_earth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_earth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_img_moon = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_img_moon, &ui_img_moon_moon_1_png);
    lv_obj_set_width(ui_img_moon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_img_moon, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_img_moon, -4);
    lv_obj_set_y(ui_img_moon, -61);
    lv_obj_set_align(ui_img_moon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_img_moon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_img_moon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_phase = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_phase, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_phase, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_phase, 38);
    lv_obj_set_y(ui_phase, 3);
    lv_obj_set_align(ui_phase, LV_ALIGN_CENTER);
    lv_label_set_text(ui_phase, "Moon Phase");
    lv_obj_set_style_text_color(ui_phase, lv_color_hex(0xDBDBDB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_phase, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_letter_space(ui_phase, 1, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_line_space(ui_phase, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_phase, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_phase, &ui_font_datefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_time = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_time, -41);
    lv_obj_set_y(ui_time, 35);
    lv_obj_set_align(ui_time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_time, "10:30:00");
    lv_obj_set_style_text_color(ui_time, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_time, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_time, &ui_font_timefont, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_date = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_date, 28);
    lv_obj_set_y(ui_date, 3);
    lv_obj_set_align(ui_date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_date, "20 AUG 26");
    lv_obj_set_style_text_align(ui_date, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_date, &ui_font_datefont, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_starsbg = NULL;
    ui_img_earth = NULL;
    ui_img_moon = NULL;
    ui_phase = NULL;
    ui_time = NULL;
    ui_date = NULL;

}
